
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Apr 22 15:07:52 EDT 2018
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LBRACKET = 34;
  public static final int MULT = 20;
  public static final int LPAREN = 30;
  public static final int INT = 37;
  public static final int MINUS = 19;
  public static final int STATIC = 5;
  public static final int RPAREN = 31;
  public static final int SEMICOLON = 36;
  public static final int NOT = 23;
  public static final int AND = 16;
  public static final int LESSTHAN = 17;
  public static final int COMMA = 22;
  public static final int CLASS = 2;
  public static final int PLUS = 18;
  public static final int MAIN = 27;
  public static final int IF = 12;
  public static final int THIS = 26;
  public static final int ID = 38;
  public static final int DOT = 33;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int RBRACKET = 35;
  public static final int TRUE = 24;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int INT_TYPE = 10;
  public static final int VOID = 6;
  public static final int EQ = 15;
  public static final int LBRACE = 28;
  public static final int ELSE = 13;
  public static final int WHILE = 14;
  public static final int PUBLIC = 4;
  public static final int RBRACE = 29;
  public static final int EXTENDS = 3;
  public static final int STRING = 7;
  public static final int FALSE = 25;
  public static final int PRINT = 32;
  public static final int LENGTH = 21;
  public static final int BOOLEAN_TYPE = 11;
}

